"""add timezone

Revision ID: 05ccae6dd57d
Revises: 0e29310e3682
Create Date: 2026-04-07 17:35:40.303288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ccae6dd57d'
down_revision: Union[str, Sequence[str], None] = '0e29310e3682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings'), table_name='image_embedding', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index('ix_embeddings_hnsw', 'image_embedding', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_foreign_key(None, 'image_embedding', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.add_column('images', sa.Column('timezone', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_location_fsq_id_search'), table_name='locations')
    op.drop_index(op.f('idx_location_key_search'), table_name='locations')
    op.drop_index(op.f('idx_location_name_country'), table_name='locations')
    op.drop_constraint(op.f('locations_key_key'), 'locations', type_='unique')
    op.create_index('ix_locations_fsq_id', 'locations', ['fsq_id'], unique=False)
    op.create_index('ix_locations_key', 'locations', ['key'], unique=False)
    op.create_index('ix_locations_name_country', 'locations', ['name', 'country'], unique=False)
    op.create_index('ix_locations_stop', 'locations', ['stop'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_locations_stop', table_name='locations')
    op.drop_index('ix_locations_name_country', table_name='locations')
    op.drop_index('ix_locations_key', table_name='locations')
    op.drop_index('ix_locations_fsq_id', table_name='locations')
    op.create_unique_constraint(op.f('locations_key_key'), 'locations', ['key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_location_name_country'), 'locations', ['name', 'country'], unique=False)
    op.create_index(op.f('idx_location_key_search'), 'locations', ['key'], unique=False)
    op.create_index(op.f('idx_location_fsq_id_search'), 'locations', ['fsq_id'], unique=False)
    op.drop_column('images', 'timezone')
    op.drop_constraint(None, 'image_embedding', type_='foreignkey')
    op.drop_index('ix_embeddings_hnsw', table_name='image_embedding', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_embeddings'), 'image_embedding', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
