"""Add annotation table

Revision ID: 1da6097b296a
Revises: 42a44d5da973
Create Date: 2026-04-07 19:41:21.291721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da6097b296a'
down_revision: Union[str, Sequence[str], None] = '42a44d5da973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('annotations', sa.Column('author', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'author')
    op.drop_column('annotations', 'timestamp')
    # ### end Alembic commands ###
