"""vbs_log client_ip + dres_submission

Revision ID: 24e39fa5a7c9
Revises: 7515676b4f11
Create Date: 2026-06-15 19:21:46.468453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '24e39fa5a7c9'
down_revision: Union[str, Sequence[str], None] = '7515676b4f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dres_submission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.BigInteger(), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('evaluation_id', sa.String(length=100), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dres_submission_evaluation', 'dres_submission', ['evaluation_id'], unique=False)
    op.create_index('ix_dres_submission_ts', 'dres_submission', ['submitted_at'], unique=False)
    op.add_column('vbs_log', sa.Column('client_ip', sa.String(length=64), nullable=True))
    op.drop_column('vbs_log', 'member_id')
    op.drop_column('vbs_log', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vbs_log', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vbs_log', sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('vbs_log', 'client_ip')
    op.drop_index('ix_dres_submission_ts', table_name='dres_submission')
    op.drop_index('ix_dres_submission_evaluation', table_name='dres_submission')
    op.drop_table('dres_submission')
    # ### end Alembic commands ###
