"""add skin temperature

Revision ID: 2a42affd58d3
Revises: 937a7d18329e
Create Date: 2026-06-03 13:10:15.235664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '2a42affd58d3'
down_revision: Union[str, Sequence[str], None] = '937a7d18329e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bio_skin_temperature',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'time_stamp', name='uq_skin_temp_device_time')
    )
    op.create_index('ix_skin_temp_device_time', 'bio_skin_temperature', ['device_id', 'time_stamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skin_temp_device_time', table_name='bio_skin_temperature')
    op.drop_table('bio_skin_temperature')
    # ### end Alembic commands ###
