"""add key to be unique

Revision ID: 2a5d5965d461
Revises: 05ccae6dd57d
Create Date: 2026-04-07 17:52:25.320619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5d5965d461'
down_revision: Union[str, Sequence[str], None] = '05ccae6dd57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'locations', ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='unique')
    # ### end Alembic commands ###
