"""add constraints

Revision ID: 49eeea9c5264
Revises: 6173fec75fca
Create Date: 2026-05-08 16:16:55.454538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '49eeea9c5264'
down_revision: Union[str, Sequence[str], None] = '6173fec75fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_raw_gps_time', 'raw_gps', ['timestamp'], unique=False)
    op.create_unique_constraint('uq_raw_gps_device_time', 'raw_gps', ['device_id', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_raw_gps_device_time', 'raw_gps', type_='unique')
    op.drop_index('ix_raw_gps_time', table_name='raw_gps')
    # ### end Alembic commands ###
