"""add cluster_id

Revision ID: 4b760b99efb6
Revises: 9b40c22187da
Create Date: 2026-04-16 17:19:48.186717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '4b760b99efb6'
down_revision: Union[str, Sequence[str], None] = '9b40c22187da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people_clusters', sa.Column('cluster_label', sa.Text(), nullable=False))
    op.add_column('people_clusters', sa.Column('center_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False))
    op.create_index('ix_people_clusters_label', 'people_clusters', ['cluster_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_people_clusters_label', table_name='people_clusters')
    op.drop_column('people_clusters', 'center_embedding')
    op.drop_column('people_clusters', 'cluster_label')
    # ### end Alembic commands ###
