"""add gps_stop_segments

Revision ID: 5a3858665d2c
Revises: a3c5e7f9b2d1
Create Date: 2026-07-31 18:32:41.008399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '5a3858665d2c'
down_revision: Union[str, Sequence[str], None] = 'a3c5e7f9b2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps_stop_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('place_id', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device', 'start_time', name='uq_gps_stop_seg_device_start')
    )
    op.create_index('ix_gps_stop_seg_device_date', 'gps_stop_segments', ['device', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gps_stop_seg_device_date', table_name='gps_stop_segments')
    op.drop_table('gps_stop_segments')
    # ### end Alembic commands ###
