"""Change Location

Revision ID: 5b098c80449e
Revises: 2b2391156da8
Create Date: 2026-06-09 15:17:57.146475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '5b098c80449e'
down_revision: Union[str, Sequence[str], None] = '2b2391156da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('suburb', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('region', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('postcode', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('osm_type', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('osm_id', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('wikidata_id', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('categories', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'categories')
    op.drop_column('locations', 'description')
    op.drop_column('locations', 'wikidata_id')
    op.drop_column('locations', 'osm_id')
    op.drop_column('locations', 'osm_type')
    op.drop_column('locations', 'postcode')
    op.drop_column('locations', 'region')
    op.drop_column('locations', 'city')
    op.drop_column('locations', 'suburb')
    # ### end Alembic commands ###
