"""add biometrics

Revision ID: 5dfe9e6e9f1a
Revises: 49eeea9c5264
Create Date: 2026-05-26 15:38:19.505623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '5dfe9e6e9f1a'
down_revision: Union[str, Sequence[str], None] = '49eeea9c5264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('sensor_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accelerometer_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['measurement_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gyroscope_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['measurement_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heart_rate_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_status', sa.Boolean(), nullable=False),
    sa.Column('contact_status_supported', sa.Boolean(), nullable=False),
    sa.Column('corrected_hr', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('ppg_quality', sa.Integer(), nullable=False),
    sa.Column('rr_available', sa.Boolean(), nullable=False),
    sa.Column('rrs_ms', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['measurement_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magnetometer_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['measurement_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ppg_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_samples', sa.JSON(), nullable=False),
    sa.Column('status_bits', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['measurement_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ppi_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_bit', sa.Boolean(), nullable=False),
    sa.Column('error_estimate', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('ppi', sa.Integer(), nullable=False),
    sa.Column('skin_contact_status', sa.Boolean(), nullable=False),
    sa.Column('skin_contact_supported', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['measurement_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ppi_data')
    op.drop_table('ppg_data')
    op.drop_table('magnetometer_data')
    op.drop_table('heart_rate_data')
    op.drop_table('gyroscope_data')
    op.drop_table('accelerometer_data')
    op.drop_table('measurement_data')
    # ### end Alembic commands ###
