"""change timestamp to datetime

Revision ID: 6173fec75fca
Revises: 65bcc83ff193
Create Date: 2026-05-08 16:05:44.031205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '6173fec75fca'
down_revision: Union[str, Sequence[str], None] = '65bcc83ff193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_gps', 'timestamp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_gps', 'timestamp',
               existing_type=sa.DateTime(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
