"""add timezone

Revision ID: 65bcc83ff193
Revises: c5a33d1be25c
Create Date: 2026-05-08 16:03:16.303522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '65bcc83ff193'
down_revision: Union[str, Sequence[str], None] = 'c5a33d1be25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_gps', sa.Column('timezone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_gps', 'timezone')
    # ### end Alembic commands ###
