"""add user_feedback table

Revision ID: 6f50e30d6e19
Revises: 5a3858665d2c
Create Date: 2026-08-07 13:14:48.959275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f50e30d6e19'
down_revision: Union[str, Sequence[str], None] = '5a3858665d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('RATING', 'FLAG', 'REPORT', name='feedbackkind'), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=True),
    sa.Column('target_id', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'REVIEWED', 'RESOLVED', name='feedbackstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_feedback_kind_status', 'user_feedback', ['kind', 'status'], unique=False)
    op.create_index('ix_user_feedback_username', 'user_feedback', ['username'], unique=False)
    # Partial unique index: at most one rating per user per target (flags/reports may repeat).
    op.create_index(
        'uq_user_feedback_rating_target', 'user_feedback',
        ['username', 'target_type', 'target_id'], unique=True,
        postgresql_where=sa.text("kind = 'RATING'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_feedback_rating_target', table_name='user_feedback')
    op.drop_index('ix_user_feedback_username', table_name='user_feedback')
    op.drop_index('ix_user_feedback_kind_status', table_name='user_feedback')
    op.drop_table('user_feedback')
    # ### end Alembic commands ###
