"""remove cluster label index

Revision ID: 74c20e7d0f41
Revises: 82db487a2083
Create Date: 2026-04-18 13:59:52.678390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '74c20e7d0f41'
down_revision: Union[str, Sequence[str], None] = '82db487a2083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_people_label'), table_name='image_people')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_people_label'), 'image_people', ['label'], unique=False)
    # ### end Alembic commands ###
