"""add vbs_log table

Revision ID: 7515676b4f11
Revises: c39a34631f86
Create Date: 2026-06-15 19:12:38.562094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '7515676b4f11'
down_revision: Union[str, Sequence[str], None] = 'c39a34631f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vbs_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('received', sa.BigInteger(), nullable=False),
    sa.Column('event_ts', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_id', sa.String(length=100), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vbs_log_evaluation', 'vbs_log', ['evaluation_id'], unique=False)
    op.create_index('ix_vbs_log_event_ts', 'vbs_log', ['event_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vbs_log_event_ts', table_name='vbs_log')
    op.drop_index('ix_vbs_log_evaluation', table_name='vbs_log')
    op.drop_table('vbs_log')
    # ### end Alembic commands ###
