"""add biometrics columns

Revision ID: 7d433dc5dc60
Revises: 5dfe9e6e9f1a
Create Date: 2026-05-26 16:06:27.315919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '7d433dc5dc60'
down_revision: Union[str, Sequence[str], None] = '5dfe9e6e9f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bio_accelerometer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'time_stamp', name='uq_acc_device_time')
    )
    op.create_index('ix_acc_device_time', 'bio_accelerometer', ['device_id', 'time_stamp'], unique=False)
    op.create_table('bio_gyroscope',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'time_stamp', name='uq_gyro_device_time')
    )
    op.create_index('ix_gyro_device_time', 'bio_gyroscope', ['device_id', 'time_stamp'], unique=False)
    op.create_table('bio_heart_rate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('contact_status', sa.Boolean(), nullable=False),
    sa.Column('contact_status_supported', sa.Boolean(), nullable=False),
    sa.Column('corrected_hr', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('ppg_quality', sa.Integer(), nullable=False),
    sa.Column('rr_available', sa.Boolean(), nullable=False),
    sa.Column('rrs_ms', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'time_stamp', name='uq_hr_device_time')
    )
    op.create_index('ix_hr_device_time', 'bio_heart_rate', ['device_id', 'time_stamp'], unique=False)
    op.create_table('bio_magnetometer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'time_stamp', name='uq_mag_device_time')
    )
    op.create_index('ix_mag_device_time', 'bio_magnetometer', ['device_id', 'time_stamp'], unique=False)
    op.create_table('bio_ppg',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('channel_samples', sa.JSON(), nullable=False),
    sa.Column('status_bits', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'time_stamp', name='uq_ppg_device_time')
    )
    op.create_index('ix_ppg_device_time', 'bio_ppg', ['device_id', 'time_stamp'], unique=False)
    op.create_table('bio_ppi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('blocker_bit', sa.Boolean(), nullable=False),
    sa.Column('error_estimate', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('ppi', sa.Integer(), nullable=False),
    sa.Column('skin_contact_status', sa.Boolean(), nullable=False),
    sa.Column('skin_contact_supported', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ppi_device_time', 'bio_ppi', ['device_id', 'time_stamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ppi_device_time', table_name='bio_ppi')
    op.drop_table('bio_ppi')
    op.drop_index('ix_ppg_device_time', table_name='bio_ppg')
    op.drop_table('bio_ppg')
    op.drop_index('ix_mag_device_time', table_name='bio_magnetometer')
    op.drop_table('bio_magnetometer')
    op.drop_index('ix_hr_device_time', table_name='bio_heart_rate')
    op.drop_table('bio_heart_rate')
    op.drop_index('ix_gyro_device_time', table_name='bio_gyroscope')
    op.drop_table('bio_gyroscope')
    op.drop_index('ix_acc_device_time', table_name='bio_accelerometer')
    op.drop_table('bio_accelerometer')
    # ### end Alembic commands ###
