"""Add relationship for whitelist

Revision ID: 7e94d9fb3e1b
Revises: dab3d8842e9a
Create Date: 2026-06-11 12:25:22.275817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '7e94d9fb3e1b'
down_revision: Union[str, Sequence[str], None] = 'dab3d8842e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
