"""add index to imageperson

Revision ID: 82db487a2083
Revises: 3f3568e188d3
Create Date: 2026-04-18 13:59:08.826560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '82db487a2083'
down_revision: Union[str, Sequence[str], None] = '3f3568e188d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_people_id', 'image_people', ['id'], unique=False)
    op.create_index('ix_people_label', 'image_people', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_people_label', table_name='image_people')
    op.drop_index('ix_people_id', table_name='image_people')
    # ### end Alembic commands ###
