"""Add indexes

Revision ID: 842455f262a2
Revises: 992b036e4f37
Create Date: 2026-06-08 22:25:28.889861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '842455f262a2'
down_revision: Union[str, Sequence[str], None] = '992b036e4f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bio_accelerometer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'time_stamp', name='uq_acc_device_time')
    )
    op.create_index('ix_acc_device_time', 'bio_accelerometer', ['device_id', 'time_stamp'], unique=False)
    op.create_table('bio_gyroscope',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'time_stamp', name='uq_gyro_device_time')
    )
    op.create_index('ix_gyro_device_time', 'bio_gyroscope', ['device_id', 'time_stamp'], unique=False)
    op.create_table('bio_heart_rate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('contact_status', sa.Boolean(), nullable=False),
    sa.Column('contact_status_supported', sa.Boolean(), nullable=False),
    sa.Column('corrected_hr', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('ppg_quality', sa.Integer(), nullable=False),
    sa.Column('rr_available', sa.Boolean(), nullable=False),
    sa.Column('rrs_ms', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'time_stamp', name='uq_hr_device_time')
    )
    op.create_index('ix_hr_device_time', 'bio_heart_rate', ['device_id', 'time_stamp'], unique=False)
    op.create_table('bio_magnetometer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'time_stamp', name='uq_mag_device_time')
    )
    op.create_index('ix_mag_device_time', 'bio_magnetometer', ['device_id', 'time_stamp'], unique=False)
    op.create_table('bio_ppg',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('channel_samples', sa.JSON(), nullable=False),
    sa.Column('status_bits', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'time_stamp', name='uq_ppg_device_time')
    )
    op.create_index('ix_ppg_device_time', 'bio_ppg', ['device_id', 'time_stamp'], unique=False)
    op.create_table('bio_ppi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('blocker_bit', sa.Boolean(), nullable=False),
    sa.Column('error_estimate', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('ppi', sa.Integer(), nullable=False),
    sa.Column('skin_contact_status', sa.Boolean(), nullable=False),
    sa.Column('skin_contact_supported', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ppi_device_time', 'bio_ppi', ['device_id', 'time_stamp'], unique=False)
    op.create_table('bio_skin_temperature',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'time_stamp', name='uq_skin_temp_device_time')
    )
    op.create_index('ix_skin_temp_device_time', 'bio_skin_temperature', ['device_id', 'time_stamp'], unique=False)
    op.create_table('raw_gps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'timestamp', name='uq_raw_gps_device_time')
    )
    op.create_index('ix_raw_gps_device', 'raw_gps', ['device_id'], unique=False)
    op.create_index('ix_raw_gps_time', 'raw_gps', ['timestamp'], unique=False)
    op.create_table('sensor_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('device_nickname', sa.Text(), nullable=True),
    sa.Column('secret', sa.Text(), nullable=True),
    sa.Column('sensor_type', sa.Text(), nullable=False),
    sa.Column('associated_user', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['associated_user'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'sensor_type', name='uq_sensor_device_id_type')
    )
    op.create_index('ix_sensor_devices_associated_user', 'sensor_devices', ['associated_user'], unique=False)
    op.create_index('ix_sensor_devices_device_id', 'sensor_devices', ['device_id'], unique=False)
    op.create_index('ix_people_id', 'image_people', ['id'], unique=False)
    op.add_column('images', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('height', sa.Integer(), nullable=True))
    op.create_index('ix_images_device_date_deleted', 'images', ['device', 'date', 'deleted'], unique=False)
    op.create_index('ix_images_device_deleted_time', 'images', ['device', 'deleted', 'deleted_time'], unique=False)
    op.create_unique_constraint('uq_device_image_path', 'images', ['device', 'image_path'])
    op.add_column('locations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('locations', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'people_clusters', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people_clusters', type_='unique')
    op.drop_column('locations', 'longitude')
    op.drop_column('locations', 'latitude')
    op.drop_constraint('uq_device_image_path', 'images', type_='unique')
    op.drop_index('ix_images_device_deleted_time', table_name='images')
    op.drop_index('ix_images_device_date_deleted', table_name='images')
    op.drop_column('images', 'height')
    op.drop_column('images', 'width')
    op.drop_index('ix_people_id', table_name='image_people')
    op.drop_index('ix_sensor_devices_device_id', table_name='sensor_devices')
    op.drop_index('ix_sensor_devices_associated_user', table_name='sensor_devices')
    op.drop_table('sensor_devices')
    op.drop_index('ix_raw_gps_time', table_name='raw_gps')
    op.drop_index('ix_raw_gps_device', table_name='raw_gps')
    op.drop_table('raw_gps')
    op.drop_index('ix_skin_temp_device_time', table_name='bio_skin_temperature')
    op.drop_table('bio_skin_temperature')
    op.drop_index('ix_ppi_device_time', table_name='bio_ppi')
    op.drop_table('bio_ppi')
    op.drop_index('ix_ppg_device_time', table_name='bio_ppg')
    op.drop_table('bio_ppg')
    op.drop_index('ix_mag_device_time', table_name='bio_magnetometer')
    op.drop_table('bio_magnetometer')
    op.drop_index('ix_hr_device_time', table_name='bio_heart_rate')
    op.drop_table('bio_heart_rate')
    op.drop_index('ix_gyro_device_time', table_name='bio_gyroscope')
    op.drop_table('bio_gyroscope')
    op.drop_index('ix_acc_device_time', table_name='bio_accelerometer')
    op.drop_table('bio_accelerometer')
    # ### end Alembic commands ###
