"""add meal_profile table

Revision ID: 84ab6286c4f5
Revises: b5d4c3a2e1f0
Create Date: 2026-06-14 06:50:42.896190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84ab6286c4f5'
down_revision: Union[str, Sequence[str], None] = 'b5d4c3a2e1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device', sa.Text(), nullable=False),
    sa.Column('meal', sa.Text(), nullable=False),
    sa.Column('usual_minute', sa.Integer(), nullable=False),
    sa.Column('grace_minute', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device', 'meal', name='uq_meal_profile_device_meal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_profile')
    # ### end Alembic commands ###
