"""add width and height

Revision ID: 8703c7a9bb11
Revises: 74c20e7d0f41
Create Date: 2026-04-18 16:01:10.727488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '8703c7a9bb11'
down_revision: Union[str, Sequence[str], None] = '74c20e7d0f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'height')
    op.drop_column('images', 'width')
    # ### end Alembic commands ###
