"""add raw gps table

Revision ID: 8aa5c7cfd67d
Revises: a2a8f490b83b
Create Date: 2026-05-08 14:45:08.307620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '8aa5c7cfd67d'
down_revision: Union[str, Sequence[str], None] = 'a2a8f490b83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_gps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_gps_device', 'raw_gps', ['device_id'], unique=False)
    op.create_index('ix_raw_gps_time', 'raw_gps', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_gps_time', table_name='raw_gps')
    op.drop_index('ix_raw_gps_device', table_name='raw_gps')
    op.drop_table('raw_gps')
    # ### end Alembic commands ###
