"""device_id doesn't have to be unique

Revision ID: 8e034ac1494b
Revises: 2a42affd58d3
Create Date: 2026-06-03 14:12:31.682554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '8e034ac1494b'
down_revision: Union[str, Sequence[str], None] = '2a42affd58d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sensor_devices_device_id_key'), 'sensor_devices', type_='unique')
    op.create_index('ix_sensor_devices_sensor_type', 'sensor_devices', ['sensor_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sensor_devices_sensor_type', table_name='sensor_devices')
    op.create_unique_constraint(op.f('sensor_devices_device_id_key'), 'sensor_devices', ['device_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
