"""add annotation relationship

Revision ID: 931fc9649d9a
Revises: 9aea360a485d
Create Date: 2026-04-09 14:57:17.792162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '931fc9649d9a'
down_revision: Union[str, Sequence[str], None] = '9aea360a485d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('anno_type', sa.Enum('RECTANGLE', 'POLYGON', 'POLYLINE', 'KEYPOINT', name='annotationtype'), nullable=False),
    sa.Column('points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotations')
    # ### end Alembic commands ###
