"""add relative bbox

Revision ID: 992b036e4f37
Revises: 9d7e698bd15e
Create Date: 2026-04-14 13:54:18.702025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '992b036e4f37'
down_revision: Union[str, Sequence[str], None] = '9d7e698bd15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_objects', sa.Column('rel_bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('image_people', sa.Column('rel_bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_people', 'rel_bbox')
    op.drop_column('image_objects', 'rel_bbox')
    # ### end Alembic commands ###
