"""add annotation relationship

Revision ID: 9aea360a485d
Revises: 973f2a7144b7
Create Date: 2026-04-09 14:31:30.807974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '9aea360a485d'
down_revision: Union[str, Sequence[str], None] = '973f2a7144b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
