"""add cluster_id

Revision ID: 9b40c22187da
Revises: e4be4986ac15
Create Date: 2026-04-16 17:10:36.005087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '9b40c22187da'
down_revision: Union[str, Sequence[str], None] = 'e4be4986ac15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_people', sa.Column('cluster_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'image_people', 'people_clusters', ['cluster_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'people_clusters', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people_clusters', type_='unique')
    op.drop_constraint(None, 'image_people', type_='foreignkey')
    op.drop_column('image_people', 'cluster_id')
    # ### end Alembic commands ###
