"""add cluster table

Revision ID: 9d7e698bd15e
Revises: 931fc9649d9a
Create Date: 2026-04-13 16:44:15.938382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = '9d7e698bd15e'
down_revision: Union[str, Sequence[str], None] = '931fc9649d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('cluster_label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_people_clusters_label', 'people_clusters', ['cluster_label'], unique=False)
    op.add_column('image_people', sa.Column('cluster_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_people_cluster'), table_name='image_people')
    op.create_foreign_key(None, 'image_people', 'people_clusters', ['cluster_id'], ['id'], ondelete='SET NULL')
    op.drop_column('image_people', 'cluster_label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_people', sa.Column('cluster_label', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'image_people', type_='foreignkey')
    op.create_index(op.f('ix_people_cluster'), 'image_people', ['cluster_label'], unique=False)
    op.drop_column('image_people', 'cluster_id')
    op.drop_index('ix_people_clusters_label', table_name='people_clusters')
    op.drop_table('people_clusters')
    # ### end Alembic commands ###
