"""add Image constraint

Revision ID: a2a8f490b83b
Revises: 8703c7a9bb11
Create Date: 2026-04-18 23:45:49.047896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = 'a2a8f490b83b'
down_revision: Union[str, Sequence[str], None] = '8703c7a9bb11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('images_id_idx'), table_name='images', postgresql_with={'deduplicate_items': 'true'})
    op.drop_index(op.f('images_width_idx'), table_name='images', postgresql_with={'deduplicate_items': 'true'})
    op.create_unique_constraint('uq_device_image_path', 'images', ['device', 'image_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_device_image_path', 'images', type_='unique')
    op.create_index(op.f('images_width_idx'), 'images', ['width'], unique=False, postgresql_with={'deduplicate_items': 'true'})
    op.create_index(op.f('images_id_idx'), 'images', ['id'], unique=False, postgresql_with={'deduplicate_items': 'true'})
    # ### end Alembic commands ###
