"""add new tables for day summary

Revision ID: aed60be9ead9
Revises: 0638a0b7c46c
Create Date: 2026-06-09 09:38:58.434666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = 'aed60be9ead9'
down_revision: Union[str, Sequence[str], None] = '0638a0b7c46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_devices_sensor_type'), table_name='sensor_devices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sensor_devices_sensor_type'), 'sensor_devices', ['sensor_type'], unique=False)
    # ### end Alembic commands ###
