"""initial_fresh_baseline

Revision ID: c314c1c2540c
Revises: 
Create Date: 2026-06-11 11:10:20.203591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c314c1c2540c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_people', sa.Column('embedding_created_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_images_activity_group'), table_name='images')
    op.alter_column('raw_gps', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_sensor_devices_last_seen'), table_name='sensor_devices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sensor_devices_last_seen'), 'sensor_devices', ['last_seen'], unique=False)
    op.alter_column('raw_gps', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_images_activity_group'), 'images', ['activity_group'], unique=False)
    op.drop_column('image_people', 'embedding_created_at')
    # ### end Alembic commands ###
