"""Add osm

Revision ID: c39a34631f86
Revises: d1e2f3a4b5c6
Create Date: 2026-06-14 15:53:24.383526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c39a34631f86'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osm_tiles',
    sa.Column('tile_lat', sa.Float(), nullable=False),
    sa.Column('tile_lon', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tile_lat', 'tile_lon')
    )
    op.alter_column('images', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_table('osm_tiles')
    # ### end Alembic commands ###
