"""add gps table constraints

Revision ID: c5a33d1be25c
Revises: 8aa5c7cfd67d
Create Date: 2026-05-08 14:50:19.936700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = 'c5a33d1be25c'
down_revision: Union[str, Sequence[str], None] = '8aa5c7cfd67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_raw_gps_device_time', 'raw_gps', ['device_id', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_raw_gps_device_time', 'raw_gps', type_='unique')
    # ### end Alembic commands ###
