"""link sensor to user

Revision ID: cb5a9cedb80a
Revises: ed1b590aef32
Create Date: 2026-05-28 14:37:31.806471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = 'cb5a9cedb80a'
down_revision: Union[str, Sequence[str], None] = 'ed1b590aef32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_devices', sa.Column('associated_user', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sensor_devices', 'devices', ['associated_user'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_devices', type_='foreignkey')
    op.drop_column('sensor_devices', 'associated_user')
    # ### end Alembic commands ###
