""" move database

Revision ID: e4be4986ac15
Revises: 992b036e4f37
Create Date: 2026-04-16 16:22:42.904060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4be4986ac15'
down_revision: Union[str, Sequence[str], None] = '992b036e4f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('cluster_label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'cluster_label')
    )
    op.create_index('ix_people_clusters_label', 'people_clusters', ['cluster_label'], unique=False)
    op.drop_index(op.f('ix_clip_embeddings_hnsw'), table_name='clip_embedding', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index('ix_clip_embedding_hnsw', 'clip_embedding', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_embeddings_hnsw'), table_name='image_embedding', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index('ix_image_embedding_hnsw', 'image_embedding', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('image_ocr', 'rel_bbox')
    op.drop_index(op.f('ix_people_cluster'), table_name='image_people')
    op.drop_column('image_people', 'cluster_label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_people', sa.Column('cluster_label', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_people_cluster'), 'image_people', ['cluster_label'], unique=False)
    op.add_column('image_ocr', sa.Column('rel_bbox', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('ix_image_embedding_hnsw', table_name='image_embedding', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_embeddings_hnsw'), 'image_embedding', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index('ix_clip_embedding_hnsw', table_name='clip_embedding', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_clip_embeddings_hnsw'), 'clip_embedding', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index('ix_people_clusters_label', table_name='people_clusters')
    op.drop_table('people_clusters')
    # ### end Alembic commands ###
