"""add sensor device

Revision ID: ed1b590aef32
Revises: 7d433dc5dc60
Create Date: 2026-05-28 14:31:18.656705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = 'ed1b590aef32'
down_revision: Union[str, Sequence[str], None] = '7d433dc5dc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('device_nickname', sa.Text(), nullable=True),
    sa.Column('secret', sa.Text(), nullable=True),
    sa.Column('sensor_type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_index('ix_sensor_devices_device_id', 'sensor_devices', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sensor_devices_device_id', table_name='sensor_devices')
    op.drop_table('sensor_devices')
    # ### end Alembic commands ###
