"""Add relationship for whitelist

Revision ID: f10f0aef6b1b
Revises: 7e94d9fb3e1b
Create Date: 2026-06-11 12:25:43.258495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = 'f10f0aef6b1b'
down_revision: Union[str, Sequence[str], None] = '7e94d9fb3e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
