"""add push_subscription table

Revision ID: f92bdca20182
Revises: 84ab6286c4f5
Create Date: 2026-06-14 06:54:20.887342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f92bdca20182'
down_revision: Union[str, Sequence[str], None] = '84ab6286c4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', name='uq_push_sub_endpoint')
    )
    op.create_index('ix_push_sub_device', 'push_subscription', ['device'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_push_sub_device', table_name='push_subscription')
    op.drop_table('push_subscription')
    # ### end Alembic commands ###
