"""add unique constratint

Revision ID: fd549e5c9a19
Revises: cb5a9cedb80a
Create Date: 2026-05-28 14:52:38.171952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # <--- Add this line here


# revision identifiers, used by Alembic.
revision: str = 'fd549e5c9a19'
down_revision: Union[str, Sequence[str], None] = 'cb5a9cedb80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sensor_devices_associated_user', 'sensor_devices', ['associated_user'], unique=False)
    op.create_unique_constraint('uq_sensor_device_id_type', 'sensor_devices', ['device_id', 'sensor_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sensor_device_id_type', 'sensor_devices', type_='unique')
    op.drop_index('ix_sensor_devices_associated_user', table_name='sensor_devices')
    # ### end Alembic commands ###
